<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'HtProfileImage\Module'                                => __DIR__ . '/Module.php',
  'HtProfileImage\Controller\HtProfileImageController'   => __DIR__ . '/src/HtProfileImage/Controller/HtProfileImageController.php',
  'HtProfileImage\Entity\User'                           => __DIR__ . '/src/HtProfileImage/Entity/User.php',
  'HtProfileImage\Factory\ImageUploadServiceFactory'     => __DIR__ . '/src/HtProfileImage/Factory/ImageUploadServiceFactory.php',
  'HtProfileImage\Factory\ModuleOptionsFactory'          => __DIR__ . '/src/HtProfileImage/Factory/ModuleOptionsFactory.php',
  'HtProfileImage\Factory\StorageModelFactory'           => __DIR__ . '/src/HtProfileImage/Factory/StorageModelFactory.php',
  'HtProfileImage\Factory\StorageResizerProviderFactory' => __DIR__ . '/src/HtProfileImage/Factory/StorageResizerProviderFactory.php',
  'HtProfileImage\Form\GenderForm'                       => __DIR__ . '/src/HtProfileImage/Form/GenderForm.php',
  'HtProfileImage\Form\ProfileImageForm'                 => __DIR__ . '/src/HtProfileImage/Form/ProfileImageForm.php',
  'HtProfileImage\Form\ProfileImageInputFilter'          => __DIR__ . '/src/HtProfileImage/Form/ProfileImageInputFilter.php',
  'HtProfileImage\Form\ProfileImageValidator'            => __DIR__ . '/src/HtProfileImage/Form/ProfileImageValidator.php',
  'HtProfileImage\Model\StorageModel'                    => __DIR__ . '/src/HtProfileImage/Model/StorageModel.php',
  'HtProfileImage\Model\StorageModelInterface'           => __DIR__ . '/src/HtProfileImage/Model/StorageModelInterface.php',
  'HtProfileImage\Model\StorageResizerProvider'          => __DIR__ . '/src/HtProfileImage/Model/StorageResizerProvider.php',
  'HtProfileImage\Options\DisplayOptionsInterface'       => __DIR__ . '/src/HtProfileImage/Options/DisplayOptionsInterface.php',
  'HtProfileImage\Options\ModuleOptions'                 => __DIR__ . '/src/HtProfileImage/Options/ModuleOptions.php',
  'HtProfileImage\Options\StorageOptionsInterface'       => __DIR__ . '/src/HtProfileImage/Options/StorageOptionsInterface.php',
  'HtProfileImage\Service\ImageUpload'                   => __DIR__ . '/src/HtProfileImage/Service/ImageUpload.php',
  'HtProfileImage\View\Helper\ProfileImage'              => __DIR__ . '/src/HtProfileImage/View/Helper/ProfileImage.php',
);
